# Generated by Django 5.1.3 on 2024-11-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('genres', models.CharField(max_length=20)),
                ('listeners', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('franchise_name', models.CharField(max_length=64, unique=True)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('album_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('price', models.PositiveIntegerField()),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('director', models.CharField(max_length=64)),
                ('actors', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField()),
                ('franchise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('album_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('price', models.PositiveIntegerField()),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.artist')),
            ],
        ),
    ]
