# Generated by Django 5.1.3 on 2024-11-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_movie_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
