# Generated by Django 5.1.3 on 2024-11-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_artist_name_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='franchise_name',
            new_name='franchise',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album_name',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
